apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
  NODE_ENV: "production"
