apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orchestrator
spec:
  replicas: {{ .Values.orchestrator.replicaCount }}
  selector:
    matchLabels:
      app: orchestra-orchestrator
  template:
    metadata:
      labels:
        app: orchestra-orchestrator
    spec:
      containers:
        - name: orchestrator
          image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
